apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sv4mgw18m-java-quarkus
  janus-idp.io/tekton: sv4mgw18m-java-quarkus
  backstage.io/kubernetes-id: sv4mgw18m-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sv4mgw18m-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
